### ISSUE TITLE
populate_with_test_data should not fail randomly

### ISSUE THREAD

**Issue by cytadela8** [warsztatywww/aplikacjawww#275]
See https://github.com/warsztatywww/aplikacjawww/pull/274/checks?check_run_id=1640504459

Problem: ` django.db.utils.IntegrityError: UNIQUE constraint failed: auth_user.username`

**Comment by krzys-h** [comment]
Closed in #307

**Comment by krzys-h** [comment]
The fix does not work, you can't simply catch IntegrityError in tests apparently: https://stackoverflow.com/questions/21458387/transactionmanagementerror-you-cant-execute-queries-until-the-end-of-the-atom

**Comment by krzys-h** [comment]
Example of the error:
```
Synchronizing apps without migrations:
----------------------------------------------------------------------
  Creating tables...
Traceback (most recent call last):
    Running deferred SQL...
  File "/home/runner/work/aplikacjawww/aplikacjawww/wwwapp/tests/test_populate_with_test_data.py", line 14, in test_populate_command
Running migrations:
    call_command('populate_with_test_data', *args, **opts)
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/django/core/management/__init__.py", line 168, in call_command
    return command.execute(*args, **defaults)
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/home/runner/work/aplikacjawww/aplikacjawww/wwwapp/management/commands/populate_with_test_data.py", line 182, in handle
    (user, user_profile) = self.fake_user()
  File "/home/runner/work/aplikacjawww/aplikacjawww/wwwapp/management/commands/populate_with_test_data.py", line 52, in fake_user
    user = User.objects.create_user(profile_data['username'], profile_data['mail'], 'password')
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/django/contrib/auth/models.py", line 146, in create_user
    return self._create_user(username, email, password, **extra_fields)
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/django/contrib/auth/models.py", line 140, in _create_user
    user.save(using=self._db)
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 67, in save
    super().save(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/django/db/models/base.py", line 754, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/django/db/models/base.py", line 792, in save_base
    force_update, using, update_fields,
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/django/db/models/base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/django/db/models/base.py", line 935, in _do_insert
    using=using, raw=raw,
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/django/db/models/query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/django/db/backends/utils.py", line 78, in _execute
    self.db.validate_no_broken_transaction()
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/django/db/backends/base/base.py", line 448, in validate_no_broken_transaction
    "An error occurred in the current transaction. You can't "
django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.

----------------------------------------------------------------------
Ran 171 tests in 104.402s
```

**Comment by krzys-h** [comment]
Another one:
```
======================================================================
ERROR: test_populate_command (wwwapp.tests.test_populate_with_test_data.PopulateWithTestData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/aplikacjawww/aplikacjawww/wwwapp/tests/test_populate_with_test_data.py", line 14, in test_populate_command
    call_command('populate_with_test_data', *args, **opts)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/django/core/management/__init__.py", line 168, in call_command
    return command.execute(*args, **defaults)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/home/runner/work/aplikacjawww/aplikacjawww/wwwapp/management/commands/populate_with_test_data.py", line 182, in handle
    (user, user_profile) = self.fake_user()
  File "/home/runner/work/aplikacjawww/aplikacjawww/wwwapp/management/commands/populate_with_test_data.py", line 52, in fake_user
    user = User.objects.create_user(profile_data['username'], profile_data['mail'], 'password')
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/django/contrib/auth/models.py", line 146, in create_user
    return self._create_user(username, email, password, **extra_fields)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/django/contrib/auth/models.py", line 140, in _create_user
    user.save(using=self._db)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/django/contrib/auth/base_user.py", line 67, in save
    super().save(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/django/db/models/base.py", line 754, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/django/db/models/base.py", line 792, in save_base
    force_update, using, update_fields,
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/django/db/models/base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/django/db/models/base.py", line 935, in _do_insert
    using=using, raw=raw,
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/django/db/models/query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/django/db/backends/utils.py", line 78, in _execute
    self.db.validate_no_broken_transaction()
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/django/db/backends/base/base.py", line 448, in validate_no_broken_transaction
    "An error occurred in the current transaction. You can't "
django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.

----------------------------------------------------------------------
Ran 171 tests in 117.875s

FAILED (errors=1)
```

**Comment by krzys-h** [comment]
It just broke agaaaain, making me unable to proceed with the deploy action :P

**Comment by cytadela8** [comment]
```
======================================================================
ERROR: test_populate_command_creates_invoices_for_each_status_and_user (wwwapp.tests.test_populate_with_test_data.PopulateWithTestData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: wwwapp_workshoptype.year_id, wwwapp_workshoptype.name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/aplikacjawww/aplikacjawww/wwwapp/tests/test_populate_with_test_data.py", line 31, in test_populate_command_creates_invoices_for_each_status_and_user
    call_command('populate_with_test_data', quiet=True)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/runner/work/aplikacjawww/aplikacjawww/wwwapp/management/commands/populate_with_test_data.py", line 610, in handle
    _, workshops = self.create_camp_year(
  File "/home/runner/work/aplikacjawww/aplikacjawww/wwwapp/management/commands/populate_with_test_data.py", line 523, in create_camp_year
    types, categories = self._create_workshop_metadata(camp)
  File "/home/runner/work/aplikacjawww/aplikacjawww/wwwapp/management/commands/populate_with_test_data.py", line 311, in _create_workshop_metadata
    types = [self.fake_type(camp) for _ in range(self.NUM_OF_TYPES)]
  File "/home/runner/work/aplikacjawww/aplikacjawww/wwwapp/management/commands/populate_with_test_data.py", line 311, in <listcomp>
    types = [self.fake_type(camp) for _ in range(self.NUM_OF_TYPES)]
  File "/home/runner/work/aplikacjawww/aplikacjawww/wwwapp/management/commands/populate_with_test_data.py", line 193, in fake_type
    c.save()
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: wwwapp_workshoptype.year_id, wwwapp_workshoptype.name
```
